---
version: "3.5"

services:
  # ---------------------------------------------------------------- #
  geocontrib:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - geocontrib.env
    ports:
      - "8000:8000"
    volumes:
      - geocontrib_media:/home/apprunner/geocontrib_app/media
      - geocontrib_config:/home/apprunner/geocontrib_app/config
    depends_on:
      - geocontrib_db

  # ---------------------------------------------------------------- #
  geocontrib_db:
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_USER=geocontrib
      - POSTGRES_PASSWORD=geocontrib
      - POSTGRES_DB=geocontrib
    volumes:
      - geocontrib_data:/var/lib/postgresql/data/
    restart: always

volumes:
  geocontrib_data:
  geocontrib_media:
  geocontrib_config:
